### ISSUE TITLE
1.1.2. kf password issue with port listener sync. now solved! 

### ISSUE THREAD

**Issue by 2020xbg** [bitgrin/kingfish#3]
## Prerequisites

- [ ] Using yarn
- [ ] Using node 10.x
- [ ] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version :
- Link to your project :

**Comment by pharazen** [comment]
Fixed in [v1.1.2-hotfix](https://github.com/bitgrin/kingfish/releases/tag/v1.1.2-hotfix)
